apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sajjad-pods-read-only-binding
  namespace: default 
subjects:
  - kind: ServiceAccount
    name: sajjad
    namespace: default  
roleRef:
  kind: Role
  name: read-only-pods  
  apiGroup: rbac.authorization.k8s.io
